approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

plugins:
  - path: scripts/pod-install.cjs

yarnPath: .yarn/releases/yarn-4.14.1.cjs
